version: "3"

services:
  django_run:
    build: .
    volumes:
      - data:/app
    working_dir: /app
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  react:
    image: node:12
    volumes:
      - data:/app
    working_dir: /app/frontend
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - django_run
    command: >
      bash -c "npm install && npm run watch"

volumes:
  data: