version: "3.5"

x-services-volume:
  &services-volume
    - type: bind
      source: .
      target: /app

services:
  django_run:
    build: .
    volumes: *services-volume
    working_dir: /app
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000

  react:
    build: ./frontend
    working_dir: /app/frontend
    volumes: *services-volume
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    command: npm run watch
